version: '3'
services:
    web:
          build: ./app
          volumes:
            - /var/run/docker.sock/:/var/run/docker.sock
          ports:
              - 80:80
          depends_on:
            - solr
            - lucene
            - elastic
    elasticsearch:
          image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
          ports:
            - 9200:9200

    solr:
          build: https://github.com/stella-project/solr-docker.git
          container_name: solr
          volumes:
            - ~/data/sample/:/data/

    lucene:
          build: https://github.com/stella-project/lucene-ranker-docker.git
          container_name: lucene
          volumes:
            - ~/data/sample/:/data/

    elastic:
          build: https://github.com/ziyad121/elastic-docker.git
          container_name: elastic
          volumes:
            - ~/data/sample/:/data/
            links:
            - elasticsearch
          tty: true

