version: '3'
services:
    web:
          build: ./app
          volumes:
            - /var/run/docker.sock/:/var/run/docker.sock
          ports:
              - 80:80
          depends_on:
            - solr
            - lucene
            - elastic
            
            
    solr:
          build: https://github.com/ziyad121/solr-docker.git
          container_name: solr
          volumes:
            - ~/data/sample/:/data/

    lucene: 
          build:  https://github.com/ziyad121/lucene-ranker-docker.git
          container_name: lucene
          volumes:
            - ~/data/sample/:/data/

    elastic:
          build: https://github.com/ziyad121/elastic-docker.git
          container_name: elastic
          volumes:
            - ~/data/sample/:/data/
          tty: true



