version: '3'
services:
    web:
          build: ./app
          volumes:
            - /var/run/docker.sock/:/var/run/docker.sock
          ports:
              - "80:80"
          depends_on:
            - solr
            - lucene
            - elasticsearch
            - pylastic
          networks: 
            - esnet
          
    elasticsearch:
          container_name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
          volumes:
              - ~/data/sample/:/data/
          ports:
              - 9300:9300
              - 9200:9200
          networks: 
              - esnet  
    solr:
          build: https://github.com/stella-project/solr-docker.git
          container_name: solr
          volumes:
            - ~/data/sample/:/data/

    lucene:
          build: https://github.com/stella-project/lucene-ranker-docker.git
          container_name: lucene
          volumes:
            - ~/data/sample/:/data/

    pylastic:
          build: https://github.com/ziyad121/elastic-docker.git
          container_name: pylastic
          volumes:
            - ~/data/sample/:/data/
          tty: true

networks:
  esnet:
